In [1]:
import numpy as np

In [2]:
a = np.arange(6)

In [3]:
type(a)

numpy.ndarray

In [4]:
a

array([0, 1, 2, 3, 4, 5])

In [5]:
a[0]

0

In [6]:
a[1]

1

In [7]:
a[:]

array([0, 1, 2, 3, 4, 5])

In [11]:
a2 = a[np.newaxis, :]

In [12]:
a.shape

(6,)

In [14]:
a2.shape

(1, 6)

In [15]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [16]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
a[0, 1]

2

In [18]:
a[0]

array([1, 2, 3, 4])

In [19]:
import numpy as np

In [20]:
a = np.array([1, 2, 3])

In [22]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
np.ones(3)

array([1., 1., 1.])

In [24]:
np.empty(2)

array([0., 0.])

In [26]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [27]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [28]:
np.arange(4, 13, 3)

array([ 4,  7, 10])

In [29]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [32]:
b = np.ones(2, dtype = np.int64)

In [33]:
b

array([1, 1])

In [34]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [35]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [39]:
arr = np.sort(arr)

In [40]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [42]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [44]:
x

array([[1, 2],
       [3, 4]])

In [45]:
y

array([[5, 6]])

In [46]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
import numpy as np

In [49]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [50]:
array_example.ndim

3

In [51]:
array_example.size

24

In [52]:
array_example.shape

(3, 2, 4)

In [53]:
a = np.arange(6)

In [54]:
a

array([0, 1, 2, 3, 4, 5])

In [56]:
a.reshape(6, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [57]:
print(a)

[0 1 2 3 4 5]


In [58]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [59]:
a = np.array([1, 2, 3, 4, 5, 6])

In [60]:
a

array([1, 2, 3, 4, 5, 6])

In [61]:
a.shape

(6,)

In [62]:
a2 = a[np.newaxis, :]

In [63]:
a2.shape

(1, 6)

In [64]:
row_vector = a[np.newaxis, :]

In [65]:
row_vector.shape

(1, 6)

In [66]:
a[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [67]:
col_vector = a[:, np.newaxis]

In [68]:
col_vector.shape

(6, 1)

In [69]:
import numpy as np

In [70]:
data = np.array([1, 2, 3])

In [71]:
data

array([1, 2, 3])

In [72]:
data[1]

2

In [73]:
data[0:2]

array([1, 2])

In [74]:
data[1:]

array([2, 3])

In [76]:
data[-2:]

array([2, 3])

In [77]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [78]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [80]:
a<5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [86]:
a[a<5]

array([1, 2, 3, 4])

In [81]:
print(a[a < 5])

[1 2 3 4]


In [87]:
print(a[a >= 5])

[ 5  6  7  8  9 10 11 12]


In [88]:
a%2==0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [89]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [82]:
b = 2

In [83]:
if b >5 :
    print("정말 크네요")
else:
    print("좋아요")

좋아요


In [85]:
b>7

False

In [90]:
c = a[(a > 2) & (a < 11)]

In [92]:
a[(a > 2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
print(c)

[ 3  4  5  6  7  8  9 10]


In [94]:
a[(a > 5) | (a == 5)]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [95]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [97]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [99]:
np.nonzero(a < 5)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In [100]:
b=np.nonzero(a < 5)

In [101]:
b

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In [102]:
list(zip(b[0], b[1]))

[(0, 0), (0, 1), (0, 2), (0, 3)]

In [104]:
list_of_coordinates

[(0, 0), (0, 1), (0, 2), (0, 3)]

In [105]:
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [106]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
arr1 = a[3:8]

In [108]:
arr1

array([4, 5, 6, 7, 8])

In [109]:
a1 = np.array([[1, 1],
               [2, 2]])

In [110]:
a2 = np.array([[3, 3],
               [4, 4]])

In [111]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [114]:
np.concatenate((a1, a2), axis=1)

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [115]:
x = np.arange(1, 25)

In [116]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [120]:
x.reshape(2, 12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [121]:
np.arange(1, 25).reshape(2, 12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [122]:
np.hsplit(x, 3)

[array([1, 2, 3, 4, 5, 6, 7, 8]),
 array([ 9, 10, 11, 12, 13, 14, 15, 16]),
 array([17, 18, 19, 20, 21, 22, 23, 24])]

In [123]:
np.hsplit(x, (3, 4))

[array([1, 2, 3]),
 array([4]),
 array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
        22, 23, 24])]

In [124]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [125]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [126]:
a[1, 1]

6

In [129]:
a[2:]

array([[ 9, 10, 11, 12]])

In [131]:
b1 = a[0, :]

In [132]:
b1

array([1, 2, 3, 4])

In [136]:
b1 = a.copy()

In [137]:
b1[0] = 99

In [138]:
b1

array([[99, 99, 99, 99],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [139]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [140]:
data = np.array([1, 2])

In [141]:
ones = np.ones(2, dtype=int)

In [142]:
data + ones

array([2, 3])

In [143]:
data - ones

array([0, 1])

In [144]:
data * data

array([1, 4])

In [145]:
a = np.array([1, 2, 3, 4])

In [146]:
a.sum()

10

In [147]:
b = np.array([[1, 1], [2, 2]])

In [148]:
b

array([[1, 1],
       [2, 2]])

In [149]:
b.sum(axis=0)

array([3, 3])

In [150]:
b.sum(axis=1)

array([2, 4])

In [151]:
data = np.array([1.0, 2.0])

In [153]:
data * 4

array([4., 8.])

In [160]:
c = np.array([[1, 5], [2,4]])

In [161]:
c

array([[1, 5],
       [2, 4]])

In [162]:
c.max()

5

In [163]:
c.min()

1

In [164]:
a.min(axis=0)

2.0

In [165]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [166]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [167]:
data[0,1]

2

In [168]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [169]:
data[0:2, 0]

array([1, 3])

In [170]:
data.max()

6

In [171]:
data.min()

1

In [172]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [176]:
np.unique(a, return_index=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14]))